server:
  port: 8080
spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petking
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      password:
      port: 6379

jwt:
  secret-key: '4E635266546A576E5A7234753778214125442A472D4B6150645367566B587032'
  expiration: 600000000
  refresh-expiration: 600000000
redis.enabled: true
